title: Anime expressions
hero_image: images/banner.png
description: Create and style a webpage for an anime drawing tutorial
meta_title: Learn CSS | Learn web development | Anime expressions
meta_description: Learn web development for beginners with the Raspberry Pi Foundation. Learn CSS and use styles to apply layouts, colour palettes, and fonts to your webpage. 
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
landing: true
steps:
  - title: Add a header
  - title: Add a section and subheading
    completion:
      - engaged
  - title: Add a paragraph
  - title: Add a facial expression
  - title: Add some descriptive text
  - title: Style your page
  - title: Edit your style sheet
  - title: Style your header
  - title: Style your footer
    completion:
      - internal
  - title: Add more styles
  - title: Use more classes
  - title: Align your content
  - title: Style your image
  - title: Style your image
  - title: Make it responsive
  - title: Change colours and fonts
    completion:
      - external
  - title: Challenge!
    challenge: true
